=begin
#WebUntis Timetable API Documentation

#*WebUntis timetable API*  Gets from WebUntis all data needed to display a timetable. Can filter for by resource (student, teacher, room, class or lesson). Can include all periods or only changed periods. Includes current state and changes from the scheduling timetable.   How to get the data of the current timetable:  Request data providing: - a start and end date - a filter criteria     - a resource id(s) for whom to view the timetable: student/teacher/room/class/lesson/period     - a timestamp for changes only   From the response: 1. Take all periods with PeriodStatusEnum values except CANCELLED. 2. For each of these periods take all resources with ResourceStatusEnum values of REGULAR and ADDED. 3. These resources are referenced by id in the periods. 4. Look up the resource in MasterDataDto. 5. Use displayName of the resource.  Display the resulting data in a suitable format.   Version history: - v1    2022-05     stw         Initial version  - v2    2023-02     stw         multiple ids as filter parameter / period as filter parameter / text fields in PeriodDto / deprecation of detailsUrl /                                 flag for online period / related period id for moved periods / period is modified when assigned students change - v3    2023-07     stw         Error handling now identical to other Untis APIs

The version of the OpenAPI document: 2.0.0
Contact: support@untis.at
Generated by: https://openapi-generator.tech
Generator version: 7.8.0

=end

# Common files
require 'untis_timetable_client/api_client'
require 'untis_timetable_client/api_error'
require 'untis_timetable_client/version'
require 'untis_timetable_client/configuration'

# Models
require 'untis_timetable_client/models/class_dto'
require 'untis_timetable_client/models/department_dto'
require 'untis_timetable_client/models/error'
require 'untis_timetable_client/models/error_code'
require 'untis_timetable_client/models/error_data'
require 'untis_timetable_client/models/error_response'
require 'untis_timetable_client/models/exam_dto'
require 'untis_timetable_client/models/filter_by_changes_dto'
require 'untis_timetable_client/models/filter_by_resource_dto'
require 'untis_timetable_client/models/filter_dto'
require 'untis_timetable_client/models/filter_resource_type_enum'
require 'untis_timetable_client/models/header_data_dto'
require 'untis_timetable_client/models/master_data_dto'
require 'untis_timetable_client/models/master_data_object_dto'
require 'untis_timetable_client/models/period_dto'
require 'untis_timetable_client/models/period_icon_enum'
require 'untis_timetable_client/models/period_resource_dto'
require 'untis_timetable_client/models/period_status_enum'
require 'untis_timetable_client/models/period_type_enum'
require 'untis_timetable_client/models/resource_ref_dto'
require 'untis_timetable_client/models/resource_status_enum'
require 'untis_timetable_client/models/room_dto'
require 'untis_timetable_client/models/school_dto'
require 'untis_timetable_client/models/student_dto'
require 'untis_timetable_client/models/student_group_dto'
require 'untis_timetable_client/models/subject_dto'
require 'untis_timetable_client/models/teacher_dto'
require 'untis_timetable_client/models/time_grid_dto'
require 'untis_timetable_client/models/time_grid_slot_dto'
require 'untis_timetable_client/models/timetable_data_dto'
require 'untis_timetable_client/models/timetable_dto'
require 'untis_timetable_client/models/validation_error'
require 'untis_timetable_client/models/validation_error_response'

# APIs
require 'untis_timetable_client/api/timetable_api'

module UntisTimetableClient
  class << self
    # Customize default settings for the SDK using block.
    #   UntisTimetableClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
