=begin
#WebUntis Timetable API Documentation

#*WebUntis timetable API*  Gets from WebUntis all data needed to display a timetable. Can filter for by resource (student, teacher, room, class or lesson). Can include all periods or only changed periods. Includes current state and changes from the scheduling timetable.   How to get the data of the current timetable:  Request data providing: - a start and end date - a filter criteria     - a resource id(s) for whom to view the timetable: student/teacher/room/class/lesson/period     - a timestamp for changes only   From the response: 1. Take all periods with PeriodStatusEnum values except CANCELLED. 2. For each of these periods take all resources with ResourceStatusEnum values of REGULAR and ADDED. 3. These resources are referenced by id in the periods. 4. Look up the resource in MasterDataDto. 5. Use displayName of the resource.  Display the resulting data in a suitable format.   Version history: - v1    2022-05     stw         Initial version  - v2    2023-02     stw         multiple ids as filter parameter / period as filter parameter / text fields in PeriodDto / deprecation of detailsUrl /                                 flag for online period / related period id for moved periods / period is modified when assigned students change - v3    2023-07     stw         Error handling now identical to other Untis APIs

The version of the OpenAPI document: 2.0.0
Contact: support@untis.at
Generated by: https://openapi-generator.tech
Generator version: 7.8.0

=end

require 'date'
require 'time'

module UntisTimetableClient
  # A timetable period.
  class PeriodDto
    # WebUntis period Id.
    attr_accessor :id

    # WebUntis lesson Id.
    attr_accessor :lesson_id

    # External entity Id.
    attr_accessor :lesson_extern_key

    # Lesson title (DB field Lesson.name).
    attr_accessor :lesson_text

    # Booking purpose or if no booking then lesson description (DB field Lesson.text).
    attr_accessor :lesson_info

    # Period text (notes visible for students) or exam description.
    attr_accessor :notes_all

    # Substitution description.
    attr_accessor :substitution_text

    # Timestamp of last change in ISO 8601 format.
    attr_accessor :modified

    # Timestamp of beginning of period in ISO 8601 format.
    attr_accessor :start

    # Timestamp of end of period in ISO 8601 format.
    attr_accessor :_end

    attr_accessor :type

    attr_accessor :status

    # The id of a related period (e.g. other side of moved period).  Periods are moved by cancelling and adding of a period. Limitations: - A period might not be in the result if a period is outside the requested date range. - If a period is moved twice, there is only a relation between second and third period.
    attr_accessor :related_period

    attr_accessor :icons

    # The id of the corresponding time grid.
    attr_accessor :timegrid_id

    attr_accessor :exam

    # Departments of the period.
    attr_accessor :departments

    # Classes of the period.
    attr_accessor :classes

    # Student groups of the period.
    attr_accessor :studentgroups

    # Students of the period.
    attr_accessor :students

    # Subjects of the period.
    attr_accessor :subjects

    # Rooms of the period.
    attr_accessor :rooms

    # Teachers of the period.
    attr_accessor :teachers

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'lesson_id' => :'lessonId',
        :'lesson_extern_key' => :'lessonExternKey',
        :'lesson_text' => :'lessonText',
        :'lesson_info' => :'lessonInfo',
        :'notes_all' => :'notesAll',
        :'substitution_text' => :'substitutionText',
        :'modified' => :'modified',
        :'start' => :'start',
        :'_end' => :'end',
        :'type' => :'type',
        :'status' => :'status',
        :'related_period' => :'relatedPeriod',
        :'icons' => :'icons',
        :'timegrid_id' => :'timegridId',
        :'exam' => :'exam',
        :'departments' => :'departments',
        :'classes' => :'classes',
        :'studentgroups' => :'studentgroups',
        :'students' => :'students',
        :'subjects' => :'subjects',
        :'rooms' => :'rooms',
        :'teachers' => :'teachers'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'Integer',
        :'lesson_id' => :'Integer',
        :'lesson_extern_key' => :'String',
        :'lesson_text' => :'String',
        :'lesson_info' => :'String',
        :'notes_all' => :'String',
        :'substitution_text' => :'String',
        :'modified' => :'Time',
        :'start' => :'Time',
        :'_end' => :'Time',
        :'type' => :'PeriodTypeEnum',
        :'status' => :'PeriodStatusEnum',
        :'related_period' => :'Integer',
        :'icons' => :'Array<PeriodIconEnum>',
        :'timegrid_id' => :'Integer',
        :'exam' => :'ExamDto',
        :'departments' => :'Array<PeriodResourceDto>',
        :'classes' => :'Array<PeriodResourceDto>',
        :'studentgroups' => :'Array<PeriodResourceDto>',
        :'students' => :'Array<PeriodResourceDto>',
        :'subjects' => :'Array<PeriodResourceDto>',
        :'rooms' => :'Array<PeriodResourceDto>',
        :'teachers' => :'Array<PeriodResourceDto>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `UntisTimetableClient::PeriodDto` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `UntisTimetableClient::PeriodDto`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'lesson_id')
        self.lesson_id = attributes[:'lesson_id']
      end

      if attributes.key?(:'lesson_extern_key')
        self.lesson_extern_key = attributes[:'lesson_extern_key']
      end

      if attributes.key?(:'lesson_text')
        self.lesson_text = attributes[:'lesson_text']
      end

      if attributes.key?(:'lesson_info')
        self.lesson_info = attributes[:'lesson_info']
      end

      if attributes.key?(:'notes_all')
        self.notes_all = attributes[:'notes_all']
      end

      if attributes.key?(:'substitution_text')
        self.substitution_text = attributes[:'substitution_text']
      end

      if attributes.key?(:'modified')
        self.modified = attributes[:'modified']
      else
        self.modified = nil
      end

      if attributes.key?(:'start')
        self.start = attributes[:'start']
      else
        self.start = nil
      end

      if attributes.key?(:'_end')
        self._end = attributes[:'_end']
      else
        self._end = nil
      end

      if attributes.key?(:'type')
        self.type = attributes[:'type']
      else
        self.type = nil
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      else
        self.status = nil
      end

      if attributes.key?(:'related_period')
        self.related_period = attributes[:'related_period']
      end

      if attributes.key?(:'icons')
        if (value = attributes[:'icons']).is_a?(Array)
          self.icons = value
        end
      end

      if attributes.key?(:'timegrid_id')
        self.timegrid_id = attributes[:'timegrid_id']
      end

      if attributes.key?(:'exam')
        self.exam = attributes[:'exam']
      end

      if attributes.key?(:'departments')
        if (value = attributes[:'departments']).is_a?(Array)
          self.departments = value
        end
      end

      if attributes.key?(:'classes')
        if (value = attributes[:'classes']).is_a?(Array)
          self.classes = value
        end
      end

      if attributes.key?(:'studentgroups')
        if (value = attributes[:'studentgroups']).is_a?(Array)
          self.studentgroups = value
        end
      end

      if attributes.key?(:'students')
        if (value = attributes[:'students']).is_a?(Array)
          self.students = value
        end
      end

      if attributes.key?(:'subjects')
        if (value = attributes[:'subjects']).is_a?(Array)
          self.subjects = value
        end
      end

      if attributes.key?(:'rooms')
        if (value = attributes[:'rooms']).is_a?(Array)
          self.rooms = value
        end
      end

      if attributes.key?(:'teachers')
        if (value = attributes[:'teachers']).is_a?(Array)
          self.teachers = value
        end
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if !@lesson_extern_key.nil? && @lesson_extern_key.to_s.length > 100
        invalid_properties.push('invalid value for "lesson_extern_key", the character length must be smaller than or equal to 100.')
      end

      if !@lesson_text.nil? && @lesson_text.to_s.length > 255
        invalid_properties.push('invalid value for "lesson_text", the character length must be smaller than or equal to 255.')
      end

      if @modified.nil?
        invalid_properties.push('invalid value for "modified", modified cannot be nil.')
      end

      if @start.nil?
        invalid_properties.push('invalid value for "start", start cannot be nil.')
      end

      if @_end.nil?
        invalid_properties.push('invalid value for "_end", _end cannot be nil.')
      end

      if @type.nil?
        invalid_properties.push('invalid value for "type", type cannot be nil.')
      end

      if @status.nil?
        invalid_properties.push('invalid value for "status", status cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @id.nil?
      return false if !@lesson_extern_key.nil? && @lesson_extern_key.to_s.length > 100
      return false if !@lesson_text.nil? && @lesson_text.to_s.length > 255
      return false if @modified.nil?
      return false if @start.nil?
      return false if @_end.nil?
      return false if @type.nil?
      return false if @status.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] lesson_extern_key Value to be assigned
    def lesson_extern_key=(lesson_extern_key)
      if lesson_extern_key.nil?
        fail ArgumentError, 'lesson_extern_key cannot be nil'
      end

      if lesson_extern_key.to_s.length > 100
        fail ArgumentError, 'invalid value for "lesson_extern_key", the character length must be smaller than or equal to 100.'
      end

      @lesson_extern_key = lesson_extern_key
    end

    # Custom attribute writer method with validation
    # @param [Object] lesson_text Value to be assigned
    def lesson_text=(lesson_text)
      if lesson_text.nil?
        fail ArgumentError, 'lesson_text cannot be nil'
      end

      if lesson_text.to_s.length > 255
        fail ArgumentError, 'invalid value for "lesson_text", the character length must be smaller than or equal to 255.'
      end

      @lesson_text = lesson_text
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          lesson_id == o.lesson_id &&
          lesson_extern_key == o.lesson_extern_key &&
          lesson_text == o.lesson_text &&
          lesson_info == o.lesson_info &&
          notes_all == o.notes_all &&
          substitution_text == o.substitution_text &&
          modified == o.modified &&
          start == o.start &&
          _end == o._end &&
          type == o.type &&
          status == o.status &&
          related_period == o.related_period &&
          icons == o.icons &&
          timegrid_id == o.timegrid_id &&
          exam == o.exam &&
          departments == o.departments &&
          classes == o.classes &&
          studentgroups == o.studentgroups &&
          students == o.students &&
          subjects == o.subjects &&
          rooms == o.rooms &&
          teachers == o.teachers
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, lesson_id, lesson_extern_key, lesson_text, lesson_info, notes_all, substitution_text, modified, start, _end, type, status, related_period, icons, timegrid_id, exam, departments, classes, studentgroups, students, subjects, rooms, teachers].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = UntisTimetableClient.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
